In [1]:
### Pandas series

In [3]:
import numpy as np
import pandas as pd

In [4]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [9]:
###Data Frame

In [10]:
data= {
    'Name': ['Aryan', 'Shivam', 'Ashwani', 'Mohan'],
    'Age' : [23,24,26,24],
    'City' : ['Delhi','Gola','Lucknow','Jhumila'],
    'Salary' : [50000,30000,30000,40000]
}
df=pd.DataFrame(data)

In [11]:
df

      Name  Age     City  Salary
0    Aryan   23    Delhi   50000
1   Shivam   24     Gola   30000
2  Ashwani   26  Lucknow   30000
3    Mohan   24  Jhumila   40000

In [12]:
df["Name"]

0      Aryan
1     Shivam
2    Ashwani
3      Mohan
Name: Name, dtype: object

In [13]:
df[["Name","Salary"]]

      Name  Salary
0    Aryan   50000
1   Shivam   30000
2  Ashwani   30000
3    Mohan   40000

In [14]:
df["Designation"]=["AI Trainer","Doctor","Sales","Eng."]

In [15]:
df

      Name  Age     City  Salary Designation
0    Aryan   23    Delhi   50000  AI Trainer
1   Shivam   24     Gola   30000      Doctor
2  Ashwani   26  Lucknow   30000       Sales
3    Mohan   24  Jhumila   40000        Eng.

In [16]:
df.drop("Designation",axis =1,inplace=True)

In [17]:
df

      Name  Age     City  Salary
0    Aryan   23    Delhi   50000
1   Shivam   24     Gola   30000
2  Ashwani   26  Lucknow   30000
3    Mohan   24  Jhumila   40000

In [18]:
df.drop("Age", axis=1)

      Name     City  Salary
0    Aryan    Delhi   50000
1   Shivam     Gola   30000
2  Ashwani  Lucknow   30000
3    Mohan  Jhumila   40000

In [19]:
df

      Name  Age     City  Salary
0    Aryan   23    Delhi   50000
1   Shivam   24     Gola   30000
2  Ashwani   26  Lucknow   30000
3    Mohan   24  Jhumila   40000

In [20]:
df.loc[0]

Name      Aryan
Age          23
City      Delhi
Salary    50000
Name: 0, dtype: object

In [21]:
df.loc[[2,3]]

      Name  Age     City  Salary
2  Ashwani   26  Lucknow   30000
3    Mohan   24  Jhumila   40000

In [22]:
df.loc[[2,3]][["City","Salary"]]

      City  Salary
2  Lucknow   30000
3  Jhumila   40000

In [23]:
d

{1: 10, 2: 20, 3: 30}

In [24]:
# only those age is above is 30

In [27]:
df[df["Age"]>25]

      Name  Age     City  Salary
2  Ashwani   26  Lucknow   30000

In [29]:
# only want people obove 20 and there city must be pairs

In [36]:
df[(df["Age"]>20) & (df["City"]=='Lucknow')]

      Name  Age     City  Salary
2  Ashwani   26  Lucknow   30000