In [2]:
import numpy as np
import pandas as pd

In [3]:
employees = pd.DataFrame({
    "emp_id": [101, 102, 103, 104, 105],
    "name": ["Amit", "Priya", "Rahul", "Sneha", "Vikram"],
    "department": ["HR", "IT", "Finance", "IT", "Marketing"]
})

# DataFrame 2: Employee Salaries
salaries = pd.DataFrame({
    "emp_id": [101, 102, 103, 106],
    "salary": [45000, 60000, 55000, 70000],
    "bonus": [5000, 7000, 6000, 8000]
})

In [4]:
employees

   emp_id    name department
0     101    Amit         HR
1     102   Priya         IT
2     103   Rahul    Finance
3     104   Sneha         IT
4     105  Vikram  Marketing

In [5]:
salaries

   emp_id  salary  bonus
0     101   45000   5000
1     102   60000   7000
2     103   55000   6000
3     106   70000   8000

In [7]:
pd.merge(employees,salaries,on='emp_id',how='inner')

   emp_id   name department  salary  bonus
0     101   Amit         HR   45000   5000
1     102  Priya         IT   60000   7000
2     103  Rahul    Finance   55000   6000

In [8]:
pd.merge(employees,salaries,on='emp_id',how='outer')

   emp_id    name department   salary   bonus
0     101    Amit         HR  45000.0  5000.0
1     102   Priya         IT  60000.0  7000.0
2     103   Rahul    Finance  55000.0  6000.0
3     104   Sneha         IT      NaN     NaN
4     105  Vikram  Marketing      NaN     NaN
5     106     NaN        NaN  70000.0  8000.0